### PR TITLE
Update to .NET 7 and latest wasmtime & Bindle

### PR DESCRIPTION
**Pull request by ChristianWeyer**

### CODE REVIEW

**Comment by ChristianWeyer** [comment]
`@microsoft-github-policy-service agree company="Thinktecture AG"`

**Review by simongdavies — APPROVED** [review]

**Comment by simongdavies** [comment]
@ChristianWeyer Thanks for the PR, any chance you can sign your commit? This repo has a policy to require signed commits. 

Thanks !!

**Comment by ChristianWeyer** [comment]
> @ChristianWeyer Thanks for the PR, any chance you can sign your commit? This repo has a policy to require signed commits.
> 
> Thanks !!

Sure, any instructions on what I need to do? :-) @simongdavies

**Comment by ChristianWeyer** [comment]
I just added signed commits. Would this work now for you?
Thanks.

**Comment by simongdavies** [comment]
@ChristianWeyer Wonderful, that should be all good now, should merge once the actions are complete

**Comment by simongdavies** [comment]
Oh , I am sorry @ChristianWeyer seems like you need to sign the original unsigned commit (alternatively if you want to squash them and force push I think that should work).

**Comment by ChristianWeyer** [comment]
Does that look better now @simongdavies ?

**Comment by ChristianWeyer** [comment]
Just let me know if something is still missing with this PR @simongdavies 😊.

**Comment by simongdavies** [comment]
> > Just let me know if something is still missing with this PR @simongdavies 😊.
> 
> Looks good, I just started the GH Jobs, should merge shortly.

@ChristianWeyer  Sorry, I spoke too soon, your last commit https://github.com/deislabs/wagi-dotnet/pull/133/commits/2cc88762ed4e43a4d11a6176dbc0d9acd2ee1c10 was not signed , can you sign it ??

**Comment by ChristianWeyer** [comment]
> > > Just let me know if something is still missing with this PR @simongdavies 😊.
> > 
> > 
> > Looks good, I just started the GH Jobs, should merge shortly.
> 
> @ChristianWeyer Sorry, I spoke too soon, your last commit [2cc8876](https://github.com/deislabs/wagi-dotnet/commit/2cc88762ed4e43a4d11a6176dbc0d9acd2ee1c10) was not signed , can you sign it ??

That happens when you move to another machine and then 'just' add a sample to the SLN 🤪

**Comment by simongdavies** [comment]
@ChristianWeyer , I think you need to squash the two commits and force push, the unsigned one is still there

**Comment by ChristianWeyer** [comment]
> @ChristianWeyer , I think you need to squash the two commits and force push, the unsigned one is still there

Let's try again.

**Pull request merged**
